name: syngen
channels:
  - conda-forge
  - defaults
  - ejolly
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _python_abi3_support=1.0=hd8ed1ab_2
  - _r-mutex=1.0.1=anacondar_1
  - alsa-lib=1.2.14=h5eee18b_0
  - aws-c-auth=0.9.1=h194c533_5
  - aws-c-cal=0.9.8=h346e085_0
  - aws-c-common=0.12.5=hb03c661_1
  - aws-c-compression=0.3.1=h7e655bb_7
  - aws-c-event-stream=0.5.6=h1deb5b9_4
  - aws-c-http=0.10.7=had4b759_1
  - aws-c-io=0.23.2=hbff472d_2
  - aws-c-mqtt=0.13.3=h8ba2272_8
  - aws-c-s3=0.8.6=h493c25d_7
  - aws-c-sdkutils=0.2.4=h7e655bb_2
  - aws-checksums=0.2.7=h7e655bb_3
  - aws-crt-cpp=0.35.0=h719b17a_2
  - aws-sdk-cpp=1.11.606=h522d481_6
  - azure-core-cpp=1.16.1=h3a458e0_0
  - azure-identity-cpp=1.13.2=h3a5f585_1
  - azure-storage-blobs-cpp=12.15.0=h2a74896_1
  - azure-storage-common-cpp=12.11.0=h3d7a050_1
  - azure-storage-files-datalake-cpp=12.13.0=hf38f1be_1
  - babel=2.17.0=pyhd8ed1ab_0
  - binutils_impl_linux-64=2.44=h9d8b0ac_5
  - bwidget=1.10.1=ha770c72_1
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h3394656_0
  - cffi=2.0.0=py313hf46b229_1
  - commonmark=0.9.1=py_0
  - cpython=3.13.9=py313hd8ed1ab_101
  - css_inline=0.18.0=py313h843e2db_0
  - curl=8.17.0=h4e3cde8_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dbus=1.16.2=h5bd4931_0
  - double-conversion=3.3.1=h6a678d5_0
  - expat=2.7.1=h6a678d5_0
  - faicons=0.2.2=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.60.1=py313hee96239_0
  - formulae=0.5.4=pyhd8ed1ab_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - future=1.0.0=pyhd8ed1ab_2
  - gcc_impl_linux-64=15.2.0=hcacfade_7
  - gflags=2.2.2=h5888daf_1005
  - gfortran_impl_linux-64=15.2.0=h1b0a18f_7
  - glog=0.7.1=hbabe93e_0
  - graphite2=1.3.14=hecca717_2
  - great_tables=0.17.0=pyhd8ed1ab_0
  - gsl=2.7=he838d99_0
  - gxx_impl_linux-64=15.2.0=h54ccb8d_7
  - harfbuzz=12.2.0=h15599e2_0
  - htmltools=0.6.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - kernel-headers_linux-64=5.14.0=he073ed8_2
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250512.1=cxx17_hba17884_0
  - libarrow=19.0.1=h9631116_36_cpu
  - libarrow-acero=19.0.1=h635bf11_36_cpu
  - libarrow-dataset=19.0.1=h635bf11_36_cpu
  - libarrow-substrait=19.0.1=h3f74fd7_36_cpu
  - libblas=3.9.0=38_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcblas=3.9.0=38_h0358290_openblas
  - libclang-cpp21.1=21.1.5=default_h99862b1_1
  - libclang13=21.1.5=default_h746c552_1
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=hb8b1518_5
  - libcurl=8.17.0=h4e3cde8_0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-devel_linux-64=15.2.0=h73f6952_107
  - libgcc-ng=15.2.0=h69a702a_7
  - libgfortran=15.2.0=h69a702a_7
  - libgfortran-ng=15.2.0=h69a702a_7
  - libgfortran5=15.2.0=hcd61629_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.86.1=h32235b2_2
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h767d61c_7
  - libgoogle-cloud=2.39.0=hdb79228_0
  - libgoogle-cloud-storage=2.39.0=hdbdcf42_0
  - libgrpc=1.73.1=h3288cfb_1
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - libkrb5=1.21.3=h520c7b4_4
  - liblapack=3.9.0=38_h47877c9_openblas
  - libllvm21=21.1.5=hf7376ad_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.30=pthreads_h94d23a6_3
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopentelemetry-cpp=1.21.0=hb9b0907_1
  - libopentelemetry-cpp-headers=1.21.0=ha770c72_1
  - libparquet=19.0.1=h7376487_36_cpu
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h421ea60_1
  - libpq=18.0=h3675c94_0
  - libprotobuf=6.31.1=h49aed37_2
  - libre2-11=2025.11.05=h7b12aa8_0
  - libsanitizer=15.2.0=hb13aed2_7
  - libsodium=1.0.20=heac8642_0
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-devel_linux-64=15.2.0=h73f6952_107
  - libstdcxx-ng=15.2.0=h4852527_7
  - libthrift=0.22.0=h454ac66_1
  - libtiff=4.7.1=h9d88235_1
  - libutf8proc=2.11.0=hb04c3b8_0
  - libuuid=2.41.2=he9a06e4_0
  - libvulkan-loader=1.4.313.0=he857663_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxkbcommon=1.13.0=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libxslt=1.1.43=h711ed8c_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.10.0=h5888daf_1
  - make=4.4.1=hb9d3cd8_2
  - markupsafe=3.0.3=py313h3dea7bd_0
  - matplotlib=3.10.7=py313h78bf25f_0
  - matplotlib-base=3.10.7=py313h683a580_0
  - ncurses=6.5=h2d0b736_3
  - nlohmann_json=3.12.0=h54a6638_1
  - nlopt=2.10.0=py313h190977b_1
  - numpy=2.3.4=py313hf6604e3_0
  - openjpeg=2.5.4=h4e0627c_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.6.0=h26f9b46_0
  - orc=2.2.1=hd747db4_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py313h08cd8bf_1
  - pandoc=3.8.2.1=ha770c72_0
  - pango=1.56.4=hadf4263_0
  - pcre2=10.46=h1321c63_0
  - pillow=12.0.0=py313h50355cd_0
  - pip=25.3=pyh145f28c_0
  - pixman=0.46.4=h54a6638_1
  - polars=1.35.1=pyh6a1acc5_0
  - polars-runtime-32=1.35.1=py310hffdcd12_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyarrow=19.0.1=py313h78bf25f_0
  - pyarrow-core=19.0.1=py313he5f92c8_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pymer4=0.9.2=2f5b405
  - pyside6=6.9.3=py313h85046ba_1
  - python=3.13.9=hc97d973_101_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gil=3.13.9=h4df99d1_101
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=hdb19cb5_2
  - qt6-main=6.9.3=h5c1c036_0
  - r-arrow=19.0.1=r44hecca717_1
  - r-askpass=1.2.1=r44h54b55ab_1
  - r-assertthat=0.2.1=r44hc72bb7e_6
  - r-backports=1.5.0=r44h54b55ab_2
  - r-base=4.4.3=hc038350_5
  - r-base64enc=0.1_3=r44h54b55ab_1008
  - r-bayestestr=0.17.0=r44hc72bb7e_1
  - r-bit=4.6.0=r44h54b55ab_1
  - r-bit64=4.6.0_1=r44h54b55ab_1
  - r-blob=1.2.4=r44hc72bb7e_3
  - r-boot=1.3_32=r44hc72bb7e_1
  - r-broom=1.0.10=r44hc72bb7e_0
  - r-broom.mixed=0.2.9.6=r44hc72bb7e_1
  - r-bslib=0.9.0=r44hc72bb7e_1
  - r-cachem=1.1.0=r44h54b55ab_2
  - r-callr=3.7.6=r44hc72bb7e_2
  - r-cellranger=1.1.0=r44hc72bb7e_1008
  - r-cli=3.6.5=r44h3697838_1
  - r-clipr=0.8.0=r44hc72bb7e_4
  - r-coda=0.19_4.1=r44hc72bb7e_2
  - r-codetools=0.2_20=r44hc72bb7e_2
  - r-colorspace=2.1_2=r44h54b55ab_0
  - r-conflicted=1.2.0=r44h785f33e_3
  - r-cpp11=0.5.2=r44h785f33e_2
  - r-crayon=1.5.3=r44hc72bb7e_2
  - r-curl=7.0.0=r44h10955f1_1
  - r-data.table=1.17.8=r44h1c8cec4_1
  - r-datawizard=1.3.0=r44hc72bb7e_0
  - r-dbi=1.2.3=r44hc72bb7e_2
  - r-dbplyr=2.5.1=r44hc72bb7e_1
  - r-digest=0.6.37=r44h3697838_1
  - r-dplyr=1.1.4=r44h3697838_2
  - r-dtplyr=1.3.2=r44hc72bb7e_1
  - r-effectsize=1.0.1=r44hc72bb7e_1
  - r-ellipsis=0.3.2=r44h54b55ab_4
  - r-emmeans=1.11.2_8=r44hc72bb7e_1
  - r-estimability=1.5.1=r44hc72bb7e_1
  - r-evaluate=1.0.5=r44hc72bb7e_1
  - r-fansi=1.0.6=r44h54b55ab_2
  - r-farver=2.1.2=r44h3697838_2
  - r-fastmap=1.2.0=r44h3697838_2
  - r-fontawesome=0.5.3=r44hc72bb7e_1
  - r-forcats=1.0.1=r44hc72bb7e_0
  - r-fs=1.6.6=r44h3697838_1
  - r-furrr=0.3.1=r44hc72bb7e_4
  - r-future=1.67.0=r44h785f33e_1
  - r-gargle=1.6.0=r44h785f33e_1
  - r-gbrd=0.4.12=r44hc72bb7e_2
  - r-generics=0.1.4=r44hc72bb7e_1
  - r-ggplot2=4.0.0=r44h785f33e_0
  - r-globals=0.18.0=r44hc72bb7e_1
  - r-glue=1.8.0=r44h54b55ab_1
  - r-googledrive=2.1.2=r44hc72bb7e_1
  - r-googlesheets4=1.1.2=r44h785f33e_1
  - r-gtable=0.3.6=r44hc72bb7e_1
  - r-haven=2.5.5=r44h6d565e7_1
  - r-highr=0.11=r44hc72bb7e_2
  - r-hms=1.1.4=r44hc72bb7e_0
  - r-htmltools=0.5.8.1=r44h3697838_2
  - r-httr=1.4.7=r44hc72bb7e_2
  - r-ids=1.0.1=r44hc72bb7e_5
  - r-insight=1.4.2=r44hc72bb7e_1
  - r-isoband=0.2.7=r44h3697838_4
  - r-jquerylib=0.1.4=r44hc72bb7e_4
  - r-jsonlite=2.0.0=r44h54b55ab_1
  - r-knitr=1.50=r44hc72bb7e_1
  - r-labeling=0.4.3=r44hc72bb7e_2
  - r-lattice=0.22_7=r44h54b55ab_1
  - r-lifecycle=1.0.4=r44hc72bb7e_2
  - r-listenv=0.10.0=r44hc72bb7e_0
  - r-lme4=1.1_37=r44h3697838_2
  - r-lmertest=3.1_3=r44hc72bb7e_4
  - r-lubridate=1.9.4=r44h54b55ab_1
  - r-magrittr=2.0.4=r44h54b55ab_0
  - r-mass=7.3_65=r44h54b55ab_0
  - r-matrix=1.7_4=r44h0e4624f_1
  - r-memoise=2.0.1=r44hc72bb7e_4
  - r-mime=0.13=r44h54b55ab_1
  - r-minqa=1.2.8=r44ha36cffa_2
  - r-modelr=0.1.11=r44hc72bb7e_3
  - r-munsell=0.5.1=r44hc72bb7e_2
  - r-mvtnorm=1.3_3=r44h11cdb10_1
  - r-nlme=3.1_168=r44heaba542_1
  - r-nloptr=2.2.1=r44h8ae9fae_1
  - r-numderiv=2016.8_1.1=r44hc72bb7e_7
  - r-openssl=2.3.4=r44h50f7d53_0
  - r-parallelly=1.45.1=r44h54b55ab_1
  - r-parameters=0.28.2=r44hc72bb7e_1
  - r-performance=0.15.2=r44hc72bb7e_0
  - r-pillar=1.11.1=r44hc72bb7e_0
  - r-pkgconfig=2.0.3=r44hc72bb7e_5
  - r-prettyunits=1.2.0=r44hc72bb7e_2
  - r-processx=3.8.6=r44h54b55ab_1
  - r-progress=1.2.3=r44hc72bb7e_2
  - r-ps=1.9.1=r44h54b55ab_1
  - r-purrr=1.2.0=r44h54b55ab_0
  - r-r6=2.6.1=r44hc72bb7e_1
  - r-ragg=1.5.0=r44h9f1dc4d_1
  - r-rappdirs=0.3.3=r44h54b55ab_4
  - r-rbibutils=2.4=r44h54b55ab_0
  - r-rcolorbrewer=1.1_3=r44h785f33e_4
  - r-rcpp=1.1.0=r44h3697838_1
  - r-rcppeigen=0.3.4.0.2=r44h3704496_1
  - r-rdpack=2.6.4=r44hc72bb7e_1
  - r-readr=2.1.5=r44h3697838_2
  - r-readxl=1.4.5=r44h10e25cc_1
  - r-reformulas=0.4.2=r44hc72bb7e_0
  - r-rematch=2.0.0=r44hc72bb7e_2
  - r-rematch2=2.1.2=r44hc72bb7e_5
  - r-report=0.6.2=r44hc72bb7e_0
  - r-reprex=2.1.1=r44hc72bb7e_2
  - r-rlang=1.1.6=r44h3697838_1
  - r-rmarkdown=2.30=r44hc72bb7e_0
  - r-rstudioapi=0.17.1=r44hc72bb7e_1
  - r-rvest=1.0.5=r44hc72bb7e_1
  - r-s7=0.2.0=r44h54b55ab_1
  - r-sass=0.4.10=r44h3697838_1
  - r-scales=1.4.0=r44hc72bb7e_1
  - r-selectr=0.4_2=r44hc72bb7e_5
  - r-stringi=1.8.7=r44h2dae267_1
  - r-stringr=1.6.0=r44h785f33e_0
  - r-sys=3.4.3=r44h54b55ab_1
  - r-systemfonts=1.3.1=r44h74f4acd_0
  - r-textshaping=1.0.4=r44h74f4acd_0
  - r-tibble=3.3.0=r44h54b55ab_1
  - r-tidyr=1.3.1=r44h3697838_2
  - r-tidyselect=1.2.1=r44hc72bb7e_2
  - r-tidyverse=2.0.0=r44h785f33e_3
  - r-timechange=0.3.0=r44h3697838_2
  - r-tinytex=0.57=r44hc72bb7e_1
  - r-tzdb=0.5.0=r44h3697838_2
  - r-utf8=1.2.6=r44h54b55ab_1
  - r-uuid=1.2_1=r44h54b55ab_1
  - r-vctrs=0.6.5=r44h3697838_2
  - r-viridislite=0.4.2=r44hc72bb7e_3
  - r-vroom=1.6.6=r44h3697838_0
  - r-withr=3.0.2=r44hc72bb7e_1
  - r-xfun=0.54=r44h3697838_0
  - r-xml2=1.4.1=r44he78afff_0
  - r-xtable=1.8_4=r44hc72bb7e_7
  - r-yaml=2.3.10=r44h54b55ab_1
  - re2=2025.11.05=h5301d42_0
  - readline=8.2=h8c095d6_2
  - rpy2=3.6.4=py313r44h67dc6d7_1
  - s2n=1.6.0=h8399546_1
  - scikit-learn=1.7.2=py313h06d4379_0
  - scipy=1.16.3=py313h11c21cd_0
  - sed=4.9=h6688a6e_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - sysroot_linux-64=2.34=h087de78_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h8d826fa_7
  - tornado=6.5.1=py313h5eee18b_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - tzlocal=5.3.1=pyh8f84b5b_0
  - wayland=1.24.0=hdac8c69_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxcursor=1.2.3=h9b100fa_0
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxt=1.3.1=hb9d3cd8_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zlib-ng=2.2.5=hde8ca8f_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - contourpy==1.3.3
      - cycler==0.12.1
      - kiwisolver==1.4.9
      - pyparsing==3.2.5
      - rpy2-rinterface==3.6.3
      - rpy2-robjects==3.6.3
prefix: /home/ethan/miniconda3/envs/syngen3
